//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceRecorder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lame.exe")]
        public string LameExePath {
            get {
                return ((string)(this["LameExePath"]));
            }
            set {
                this["LameExePath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LENOVO-PC\\DIKSISHESOP;Initial Catalog=school;User ID=sa;Password=josg" +
            "andos")]
        public string schoolConnectionString {
            get {
                return ((string)(this["schoolConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LENOVO-PC\\DIKSISHESOP;Initial Catalog=HeartBeatRecord;Persist Securit" +
            "y Info=True;User ID=sa;Password=josgandos")]
        public string HeartBeatRecordConnectionString {
            get {
                return ((string)(this["HeartBeatRecordConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=lenovo-pc\\diksishesop;Initial Catalog=HeartRateRecord;User ID=sa;Pass" +
            "word=josgandos")]
        public string HeartRateRecordConnectionString {
            get {
                return ((string)(this["HeartRateRecordConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=lenovo-pc\\diksishesop;Initial Catalog=HeartBeatRecord;User ID=sa;Pass" +
            "word=josgandos")]
        public string HeartBeatRecordConnectionString1 {
            get {
                return ((string)(this["HeartBeatRecordConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mssql.lskk.ee.itb.ac.id;Initial Catalog=hostingShesopID;Persist Secur" +
            "ity Info=True;User ID=shesop;Password=890f805f")]
        public string hostingShesopIDConnectionString {
            get {
                return ((string)(this["hostingShesopIDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LENOVO-PC\\DIKSISHESOP;Initial Catalog=hostingShesopID;User ID=sa;Pass" +
            "word=josgandos")]
        public string hostingShesopIDConnectionString1 {
            get {
                return ((string)(this["hostingShesopIDConnectionString1"]));
            }
        }
    }
}
