#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceRecorder
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hostingShesopID")]
	public partial class db_shesop2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSTEPPY_API_t_loose_measurement(STEPPY_API_t_loose_measurement instance);
    partial void UpdateSTEPPY_API_t_loose_measurement(STEPPY_API_t_loose_measurement instance);
    partial void DeleteSTEPPY_API_t_loose_measurement(STEPPY_API_t_loose_measurement instance);
    #endregion
		
		public db_shesop2DataContext() : 
				base(global::VoiceRecorder.Properties.Settings.Default.hostingShesopIDConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public db_shesop2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_shesop2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_shesop2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_shesop2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<STEPPY_API_t_loose_measurement> STEPPY_API_t_loose_measurements
		{
			get
			{
				return this.GetTable<STEPPY_API_t_loose_measurement>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STEPPY_API_t_loose_measurement")]
	public partial class STEPPY_API_t_loose_measurement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id_measurement;
		
		private string _id_user;
		
		private string _device_type;
		
		private System.Nullable<int> _measurement_type;
		
		private System.Nullable<decimal> _value;
		
		private System.Nullable<long> _epoch_timestamp;
		
		private System.Nullable<long> _inserted_timestamp;
		
		private System.Nullable<int> _id_user_shesop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_measurementChanging(long value);
    partial void Onid_measurementChanged();
    partial void Onid_userChanging(string value);
    partial void Onid_userChanged();
    partial void Ondevice_typeChanging(string value);
    partial void Ondevice_typeChanged();
    partial void Onmeasurement_typeChanging(System.Nullable<int> value);
    partial void Onmeasurement_typeChanged();
    partial void OnvalueChanging(System.Nullable<decimal> value);
    partial void OnvalueChanged();
    partial void Onepoch_timestampChanging(System.Nullable<long> value);
    partial void Onepoch_timestampChanged();
    partial void Oninserted_timestampChanging(System.Nullable<long> value);
    partial void Oninserted_timestampChanged();
    partial void Onid_user_shesopChanging(System.Nullable<int> value);
    partial void Onid_user_shesopChanged();
    #endregion
		
		public STEPPY_API_t_loose_measurement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_measurement", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id_measurement
		{
			get
			{
				return this._id_measurement;
			}
			set
			{
				if ((this._id_measurement != value))
				{
					this.Onid_measurementChanging(value);
					this.SendPropertyChanging();
					this._id_measurement = value;
					this.SendPropertyChanged("id_measurement");
					this.Onid_measurementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="VarChar(128)")]
		public string id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_type", DbType="VarChar(20)")]
		public string device_type
		{
			get
			{
				return this._device_type;
			}
			set
			{
				if ((this._device_type != value))
				{
					this.Ondevice_typeChanging(value);
					this.SendPropertyChanging();
					this._device_type = value;
					this.SendPropertyChanged("device_type");
					this.Ondevice_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_measurement_type", DbType="Int")]
		public System.Nullable<int> measurement_type
		{
			get
			{
				return this._measurement_type;
			}
			set
			{
				if ((this._measurement_type != value))
				{
					this.Onmeasurement_typeChanging(value);
					this.SendPropertyChanging();
					this._measurement_type = value;
					this.SendPropertyChanged("measurement_type");
					this.Onmeasurement_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_epoch_timestamp", DbType="BigInt")]
		public System.Nullable<long> epoch_timestamp
		{
			get
			{
				return this._epoch_timestamp;
			}
			set
			{
				if ((this._epoch_timestamp != value))
				{
					this.Onepoch_timestampChanging(value);
					this.SendPropertyChanging();
					this._epoch_timestamp = value;
					this.SendPropertyChanged("epoch_timestamp");
					this.Onepoch_timestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inserted_timestamp", DbType="BigInt")]
		public System.Nullable<long> inserted_timestamp
		{
			get
			{
				return this._inserted_timestamp;
			}
			set
			{
				if ((this._inserted_timestamp != value))
				{
					this.Oninserted_timestampChanging(value);
					this.SendPropertyChanging();
					this._inserted_timestamp = value;
					this.SendPropertyChanged("inserted_timestamp");
					this.Oninserted_timestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user_shesop", DbType="Int")]
		public System.Nullable<int> id_user_shesop
		{
			get
			{
				return this._id_user_shesop;
			}
			set
			{
				if ((this._id_user_shesop != value))
				{
					this.Onid_user_shesopChanging(value);
					this.SendPropertyChanging();
					this._id_user_shesop = value;
					this.SendPropertyChanged("id_user_shesop");
					this.Onid_user_shesopChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
